from .helper import say_hello  # Expose say_hello at the package level 
from .helper import dot_product
from .helper import get_valid_bert_base_token_ids
from .helper import get_invalid_bert_base_token_ids
from .helper import get_valid_invalid_bert_base_token_embeddings
from .helper import generate_embedding_weights_summary_stats
from .helper import generate_embedding_norm_summary_stats
from .helper import generate_norm_similarities
from .helper import normalise_vectors
from .helper import normalise_single_vector
from .helper import residualise
from .helper import sparsify
from .helper import get_euclidean_dist
from .helper import generate_distance_matrix
from .helper import generate_reduced_array
from .helper import bert_base_inference
from .helper import bert_inference_skip_all_embeddings
from .helper import bert_base_inference_include_positional_embeddings
from .helper import get_average_valid_bert_base_embedding
from .helper import generate_normalised_random_vectors_with_one_common_component
from .helper import demean_embeddings
from .helper import generate_per_vector_summary_stats
from .helper import generate_random_embeddings_with_given_characteristics
from .helper import display_stats
from .helper import plot_histogram
from .helper import this_log
from .helper import calculate_nu_alpha_W_WTW_square_W
from .helper import calculate_nu_alpha_X_XTX_XXT
from .helper import experiment_relu_X_gelu_X_tanh_X
from .helper import this_relu
from .helper import this_sigmoid
from .helper import this_tanh
from .helper import gelu_exact
from .helper import gelu_approx
from .helper import calculate_nu_alpha_d
from .helper import calculate_nu_alpha_d_old
from .helper import row_wise_softmax
from .helper import softmax
from .helper import generate_square_weight_matrix
from .helper import generate_data_manifold
from .helper import calculate_nu
from .helper import calculate_nu_s
from .helper import raise_to_power
from .helper import inv_pareto_cdf
from .helper import calculate_stable_rank
from .helper import generate_orthogonal_matrix
from .helper import calculate_nu_twonn_dim
from .helper import calculate_PatnaikPearson_dim
from .helper import calculate_PatnaikPearson_dim_cpu
from .helper import calculate_PatnaikPearson_dim_gpu
from .helper import calculate_PatnaikPearson_dim_for_MP
from .helper import twonn_intrinsic_dimension
from .helper import plot_histogram_of_eigenvalues
from .helper import clean_array
from .helper import plot_histogram_of_values
from .helper import estimate_product_nu_over_d
from .helper import estimate_product_nu_over_d_base
from .helper import estimate_product_alpha_base
from .helper import calculate_nu_over_d_given_alpha_and_d
from .helper import calculate_nu_over_d_given_alpha
from .helper import calculate_alpha_given_nu_over_d
from .helper import get_alpha_vals_nu_over_d_vals
from .helper import smooth_this_array
from .helper import calculate_softmax_nu_over_d
from .helper import softmax_f
from .helper import calculate_softmax_alpha
from .helper import get_alpha_vals_softmax_alpha_vals
from .helper import attention_experiment_new
from .helper import calculate_nu_Sigma_for_fixed_alpha_as_d_goes_to_infinity
from .helper import calculate_nu_Sigma_nu_SigmaSquared
from .helper import calculate_nu_W_nu_WTW
from .helper import calculate_nu_W_nu_WTW_old
from .helper import generate_pareto_draws
from .helper import calculate_product_nu
from .helper import generate_random_data_of_given_intrinsic_dim
from .helper import generate_N_points_in_k_dimensional_subspace_in_R_d
from .helper import generate_N_points_in_k_dimensional_subspace_in_R_d
from .helper import run_experiment_one
from .helper import generate_N_points_on_k_sphere_in_R_d
from .helper import generate_N_points_in_unit_k_ball_in_R_d
from .helper import generate_N_points_on_surface_of_k_ellipsoid_in_R_d
from .helper import generate_N_points_in_solid_k_cube_in_R_d
from .helper import generate_N_points_on_k_dim_cubical_surface_in_R_d
from .helper import calculate_alpha_given_nu_over_d_and_d
from .helper import calculate_nu_alpha_d_analytic_array
from .helper import calculate_nu_alpha_d_analytic
from .helper import calculate_nu_and_nu_over_d_given_alpha_d_analytic
from .helper import get_nu_over_d_vals_from_alpha_vals_d
from .helper import calculate_conjectured_limiting_value_nu_over_d
from .helper import C_alpha
from .helper import this_abs
from .helper import this_log10
from .helper import product_alpha_experiment
from .helper import relu_experiment
from .helper import sigmoid_experiment
from .helper import addition_experiment
from .helper import addition_experiment_two
from .helper import concatenation_experiment
from .helper import analyse_embeddings
from .helper import plot_per_layer_graphs
from .helper import bert_token_embedding_layerwise_pp_dim_experiment
from .helper import DeepSeek_R1_Distill_Qwen_1_5B_token_embedding_layerwise_pp_dim_experiment
from .helper import DeepSeek_R1_Distill_Qwen_1_5B_token_embedding_initial_pp_dim_experiment
from .helper import normalisation_experiment
from .helper import interpolation_experiment
from .helper import softmax_experiment
from .helper import pp_dim_AB_experiment
from .helper import attention_experiment_nu_over_d